#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\IndexController::index
renew:
  path: /renew
  controller: App\Controller\IndexController::renew
